version: '3.8'

services:
  manmudra-apiuser-uservice:
    build:
      context: .
    container_name: manmudra-apiuser-uservice
    restart: always
    ports:
      - 'uport:8080'
    depends_on:
      manmudra-postgres-uservice:
        condition: service_healthy
    networks:
      - manmudra-network-uservice

  manmudra-postgres-uservice:
    image: postgres
    container_name: manmudra-postgres-uservice
    restart: always
    volumes:
      - manmudra-pgdata-uservice:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: manmudra
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresql@main
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - 'gport:5432'
    networks:
      - manmudra-network-uservice

volumes:
  manmudra-pgdata-uservice:
    name: manmudra-pgdata-uservice

networks:
  manmudra-network-uservice:
    name: manmudra-network-uservice
